mod 'homebrew',    '2.1.0',  :github_tarball => 'boxen/puppet-homebrew'
mod 'stdlib',      '4.17.1', :github_tarball => 'puppetlabs/puppetlabs-stdlib'
mod 'sudo',        '1.0.0',  :github_tarball => 'boxen/puppet-sudo'
